name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "VERSION=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Package Nintendo Switch Driver
        run: |
          cd uibutton_nintendo_switch
          zip -r ../uibutton_nintendo_switch.c4z ./*
          cd ..

      - name: Package PS5 Driver
        run: |
          cd uibutton_ps5
          zip -r ../uibutton_ps5.c4z ./*
          cd ..

      - name: Find available tag
        id: tag
        run: |
          BASE_TAG="v${{ steps.date.outputs.VERSION }}"
          TAG=$BASE_TAG
          COUNT=2
          while git ls-remote --exit-code origin refs/tags/$TAG >/dev/null 2>&1; do
            TAG="${BASE_TAG}.${COUNT}"
            COUNT=$((COUNT + 1))
          done
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git tag ${{ steps.tag.outputs.TAG }}
          git push origin ${{ steps.tag.outputs.TAG }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.date.outputs.VERSION }}
          name: Release v${{ steps.date.outputs.VERSION }}
          files: |
            uibutton_nintendo_switch.c4z
            uibutton_ps5.c4z
          generate_release_notes: true